### ISSUE TITLE
Gamestore payment processing 

### ISSUE THREAD

**Issue by armaanreza** [PacktPublishing/Python-Programming-Blueprints#10]
Hi @dfurtado 

Thank you so much for this wonderful book. Learning many new technologies through your book. At gamestore project, I don't see any implementation of payment processing service such as 'Stripe.'  I really want to launch an online store built with Django which can process payments using credit cards. Is there any guide or tutorial you can point out to implement Stripe at your gamestore project? It would be a great help. 

Regards

**Comment by dfurtado** [comment]
Hi @armaanreza ,

Thank you so much for your feedback, that means a lot to me, I have put countless hours and my heart into this project so to hear that the book was so beneficial to you definitely made my day! I would appreciate if you could write a few lines about the book on Packt website or Amazon, I would really appreciate it and it would help other developers to know more about the book before buying it.

Regarding the integration with payment providers, I decided to leave that out of the book since it was out of the scope but I have experience in integration with Braintree and they have a very nice, well documented and easy to use Python API and I believe that Stripe has something similar, you can look at https://stripe.com/docs/api/python

Regards,

//Daniel

**Comment by armaanreza** [comment]
Hi @dfurtado,

I will definitely submit a 5 star review at Amazon. You deserve it Daniel. 

Best regards
Syed
